# Generated by Django 6.0 on 2025-12-04 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='鸟类名称')),
                ('danger_level', models.IntegerField(default=1, verbose_name='危险等级(1-10)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '鸟类信息',
                'verbose_name_plural': '鸟类信息',
            },
        ),
        migrations.CreateModel(
            name='BirdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('location', models.CharField(max_length=200, verbose_name='发现位置')),
                ('intrusion_reason', models.CharField(blank=True, max_length=200, verbose_name='入侵原因')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=10, verbose_name='风险等级')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.birdspecies', verbose_name='鸟种')),
            ],
            options={
                'verbose_name': '鸟情记录',
                'verbose_name_plural': '鸟情记录',
            },
        ),
    ]
