# Generated by Django 5.2.8 on 2025-12-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_birdrecord_latitude_birdrecord_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10, unique=True, verbose_name='机场标识符')),
                ('name', models.CharField(max_length=200, verbose_name='机场名称')),
                ('airport_type', models.CharField(choices=[('large_airport', '大型机场'), ('medium_airport', '中型机场'), ('small_airport', '小型机场'), ('heliport', '直升机场'), ('seaplane_base', '水上飞机基地'), ('balloonport', '热气球场'), ('closed', '已关闭')], default='small_airport', max_length=20, verbose_name='机场类型')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('elevation_ft', models.IntegerField(blank=True, null=True, verbose_name='海拔高度(英尺)')),
                ('continent', models.CharField(blank=True, max_length=2, verbose_name='大洲')),
                ('iso_country', models.CharField(max_length=2, verbose_name='国家代码')),
                ('iso_region', models.CharField(max_length=7, verbose_name='地区代码')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('scheduled_service', models.CharField(default='no', max_length=3, verbose_name='定期航班')),
                ('icao_code', models.CharField(blank=True, max_length=4, verbose_name='ICAO代码')),
                ('iata_code', models.CharField(blank=True, max_length=3, verbose_name='IATA代码')),
                ('gps_code', models.CharField(blank=True, max_length=10, verbose_name='GPS代码')),
                ('local_code', models.CharField(blank=True, max_length=10, verbose_name='本地代码')),
                ('home_link', models.URLField(blank=True, verbose_name='官网链接')),
                ('wikipedia_link', models.URLField(blank=True, verbose_name='维基百科链接')),
                ('keywords', models.TextField(blank=True, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '机场信息',
                'verbose_name_plural': '机场信息',
            },
        ),
    ]
