# Generated by Django 5.2.8 on 2025-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('bird', '鸟情数据'), ('airport', '机场数据')], max_length=10, verbose_name='日志类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小(bytes)')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功导入数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误数')),
                ('status', models.CharField(default='processing', max_length=20, verbose_name='状态')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('error_messages', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
